In [1]:
import numpy as np
import scipy as sp
import pandas as pd

from sklearn.preprocessing import Imputer

df = pd.read_csv('train.csv')

In [2]:
df

,Unnamed: 0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X15,X16,X17,X18,X19,X20,X21,X22,X23,Y
0,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
1,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
2,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
3,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
4,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
5,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
6,6,50000,1,1,2,37,0,0,0,0,...,19394,19619,20024,2500,1815,657,1000,1000,800,0
7,7,500000,1,1,2,29,0,0,0,0,...,542653,483003,473944,55000,40000,38000,20239,13750,13770,0
8,8,100000,2,2,2,23,0,-1,-1,0,...,221,-159,567,380,601,0,581,1687,1542,0
9,9,140000,2,3,1,28,0,0,2,0,...,12211,11793,3719,3329,0,432,1000,1000,1000,0
10,10,20000,1,3,2,35,-2,-2,-2,-2,...,0,13007,13912,0,0,0,13007,1122,0,0
11,11,200000,2,3,2,34,0,0,2,0,...,2513,1828,3731,2306,12,50,300,3738,66,0
12,12,260000,2,1,2,51,-1,-1,-1,-1,...,8517,22287,13668,21818,9966,8583,22301,0,3640,0
13,13,630000,2,2,2,41,-1,0,-1,-1,...,6500,6500,2870,1000,6500,6500,6500,2870,0,0
14,14,70000,1,2,2,30,1,2,2,0,...,66782,36137,36894,3200,0,3000,3000,1500,0,1
15,15,250000,1,1,2,29,0,0,0,0,...,59696,56875,55512,3000,3000,3000,3000,3000,3000,0
16,16,50000,2,3,3,23,1,2,0,0,...,28771,29531,30211,0,1500,1100,1200,1300,1100,0
17,17,20000,1,1,2,24,0,0,2,2,...,18338,17905,19104,3200,0,1500,0,1650,0,1
18,18,320000,1,1,1,49,0,0,0,-1,...,70074,5856,195599,10358,10000,75940,20000,195599,50000,0
19,19,360000,2,1,1,49,1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
20,20,180000,2,1,2,29,1,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
21,21,130000,2,3,2,39,0,0,0,0,...,20616,11802,930,3000,1537,1000,2000,930,33764,0
22,22,120000,2,2,1,39,-1,-1,-1,-1,...,0,632,316,316,316,0,632,316,0,1
23,23,70000,2,2,2,26,2,0,0,2,...,44006,46905,46012,2007,3582,0,3601,0,1820,1
24,24,450000,2,1,1,40,-2,-2,-2,-2,...,560,0,0,19428,1473,560,0,0,1128,1
25,25,90000,1,1,2,23,0,0,0,-1,...,5398,6360,8292,5757,0,5398,1200,2045,2000,0
26,26,50000,1,3,2,23,0,0,0,0,...,28967,29829,30046,1973,1426,1001,1432,1062,997,0
27,27,60000,1,1,2,27,1,-2,-1,-1,...,-57,127,-189,0,1000,0,500,0,1000,1
28,28,50000,2,3,2,30,0,0,0,0,...,17878,18931,19617,1300,1300,1000,1500,1000,1012,0
29,29,50000,2,3,1,47,-1,-1,-1,-1,...,2040,30430,257,3415,3421,2044,30430,257,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20971,20971,210000,1,2,2,42,0,0,0,0,...,209754,212737,209083,8800,9000,9200,8000,8000,9000,0
20972,20972,60000,1,3,1,43,0,0,0,0,...,42849,17490,15633,1669,2000,1870,1000,586,619,0
20973,20973,20000,1,2,3,48,0,0,0,2,...,17333,16820,17175,1500,3500,1000,1000,1000,1000,0
20974,20974,50000,1,3,1,45,0,-1,-1,2,...,1134,1073,1312,261,2305,0,1200,1500,0,1
20975,20975,60000,1,3,1,41,0,0,0,0,...,58064,55928,57108,2826,2269,2277,2002,2081,2395,0
20976,20976,460000,1,1,2,39,0,0,0,0,...,179698,167727,136894,15495,10089,8077,6184,8047,6035,0
20977,20977,240000,1,5,1,40,-2,-2,-2,-2,...,0,0,0,2054,6984,0,0,0,0,0
20978,20978,30000,1,2,2,44,2,0,0,0,...,20865,23465,24465,1306,1500,1400,3000,1000,0,1
20979,20979,50000,1,2,1,41,0,0,0,0,...,48635,19373,20129,2500,2500,3000,1500,2000,3000,0
20980,20980,120000,1,2,1,41,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,1
20981,20981,120000,1,2,2,32,0,0,0,0,...,117041,50980,51285,4100,6000,5000,5000,58895,5000,0
20982,20982,230000,1,1,2,40,-2,-2,-2,-2,...,-868,-868,-868,7882,162,0,0,0,0,1
20983,20983,80000,1,1,2,39,0,0,0,0,...,0,780,390,8000,6000,0,390,390,540,0
20984,20984,20000,1,2,2,34,2,2,2,0,...,19492,19859,19232,3500,0,1500,805,7000,542,1
20985,20985,360000,1,2,1,33,-1,-1,-1,-1,...,101497,68960,28399,44730,22751,101691,2233,6138,16113,0
20986,20986,500000,1,1,1,30,0,0,0,0,...,78946,76689,77968,2800,3500,2818,2743,3000,10000,0
20987,20987,30000,1,2,1,45,1,2,2,2,...,18241,18446,18009,1600,2000,1600,800,0,1600,1
20988,20988,170000,1,1,2,29,-1,2,-1,2,...,12769,6283,3093,70,19136,64,6314,3107,3494,0
20989,20989,240000,1,2,2,41,0,0,0,0,...,232756,214781,219313,10000,11000,10300,7700,8000,8100,0
20990,20990,230000,1,1,1,40,-2,-2,-2,-2,...,2663,2660,2997,2018,3605,2681,2673,3012,2583,0
20991,20991,180000,1,1,2,31,1,2,2,2,...,347813,171041,181637,0,16000,6000,0,15000,7000,0
20992,20992,210000,1,3,1,38,2,2,2,2,...,78564,37154,0,12301,16,5812,218,0,0,1
20993,20993,460000,1,1,2,44,2,2,2,2,...,299739,304319,299400,12000,12500,11000,11000,0,27000,1
20994,20994,200000,1,1,1,47,1,2,2,0,...,166515,163673,145683,8013,13,8684,5500,7437,4600,1
20995,20995,80000,1,2,1,40,0,0,0,0,...,73572,73025,73087,3007,5012,3119,3007,3110,3101,0
20996,20996,50000,1,2,1,49,1,2,2,0,...,50046,19858,19278,2400,0,2300,1000,1000,1000,1
20997,20997,230000,1,2,2,38,2,2,2,2,...,187053,176805,180826,8000,8000,6500,0,7000,6500,0
20998,20998,80000,1,2,1,38,0,0,0,0,...,7467,6727,994,1631,1432,1000,520,1097,2236,0
20999,20999,200000,1,2,1,32,-1,-1,0,0,...,72739,389,389,90001,3935,3759,390,390,390,0
21000,21000,50000,1,3,1,40,-1,-1,-1,-1,...,1261,390,390,2522,170,1261,390,390,390,0